---
title: "Mappeinnlevering1"
author: "Eov016"
date: "26 1 2022"
output: pdf_document
theme : flatly
highlight : zenburn
---


```{r, include=FALSE}
options(tinytex.verbose = TRUE)

hook_output <- knitr::knit_hooks$get("output")

# set a new output hook to truncate text output
knitr::knit_hooks$set(output = function(x, options) {
  if (!is.null(n <- options$out.lines)) {
    x <- xfun::split_lines(x)
    if (length(x) > n) {
      # truncate the output
      x <- c(head(x, n), "....\n")
    }
    x <- paste(x, collapse = "\n")
  }
  hook_output(x, options)
})

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(prettydoc)
library(readr)
library(data.table)
library(dplyr)
library(tidyr)
library(tidyselect)
library(magrittr)
library(tibble)
library(ggplot2)
library(zoo)
library(lubridate)
library(xts)
library(forecast)
library(reshape2)
library(scales)
library(tidyverse)

```
**OPPGAVE 1**

```{r, include=TRUE, echo=TRUE, out.lines = 5}
uahncdc_lt_6_0.txt <- fread("http://www.nsstc.uah.edu/data/msu/v6.0/tlt/uahncdc_lt_6.0.txt",
                            header = TRUE,
                            sep = "auto",
                            stringsAsFactors = FALSE,
                            fill = TRUE)

names(uahncdc_lt_6_0.txt)<-make.names(names(uahncdc_lt_6_0.txt),unique = TRUE)
#ville sjekke class
sapply(uahncdc_lt_6_0.txt, class)
```

```{r,out.lines = 5}
#Ville se strukturen
str(uahncdc_lt_6_0.txt)
```

```{r}
#Her har jeg gjort om til en tibble etter at jeg valgte ønskede kolonner
#og fjernet rader.(Viste seg etterhvert at jeg ikke fikk bruk for "Year, "Mo")
lt_txt <- uahncdc_lt_6_0.txt %>% 
  select(Year, Globe, Mo) %>% 
  slice(-c(518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529))
head(lt_txt)
str(lt_txt)
```

```{r}
#Konverterer til numeric før jeg bruker rollmean
convert_to_double <- c("Globe", "Year", "Mo")

lt_txt[, convert_to_double] <- lt_txt[, lapply(.SD, as.double), .SDcols = convert_to_double]

str(lt_txt)
```

```{r}
#Lager ny kolonne der jeg regner zoo::rollmean som jeg plasser først
#Jeg prøvde først align ="center", men den som var lik original_grafen var "right"
lt_plot<- lt_txt %>%
  mutate(thirteen_avg = rollmean(Globe, 13,
                             align="right",
                             fill=NA)) %>%
  relocate(thirteen_avg)
  str(lt_plot)
```

```{r}
#Skrev årene inn til "labels" i scale_x_continuous
manual_years = c("1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985",
                 "1986", "1987", "1988", "1989","1990", "1991", "1992", "1993",
                 "1994", "1995", "1996", "1997", "1998", "1999", "2000","2001",
                 "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009",
                 "2010", "2011","2012", "2013", "2014", "2015", "2016", "2017", 
                 "2018", "2019", "2020", "2021")


```

\newpage

```{r, fig.width = 10, fig.height = 8}
#Når jeg hadde "Year" på x aksen ble grafen plottet uten mange ønskede
#datapunkter fordi den inneholdt så mange like årstall. Forsøkte unite()
#unite("navn", Year, Mo, sep "-"), men det ville seg ikke. Etter mye tenking
#endte jeg opp med "x = 1:517", da fikk jeg alle verdiene med og grafen ble mer
#flytende. Da måtte jeg gjøre litt ekstra manuelt i scale_x_y_continous.
lt_plot %>% 
  ggplot(aes(x = 1:517, group = 1))+
  geom_line(aes(y = Globe), linetype = 1, color ="slateblue4", lineend = "round")+
  geom_point(aes(y = Globe),alpha = 0.30, color = "slateblue4")+
  geom_line(aes(y = thirteen_avg), lwd = 1, lineend ="butt", color = "mediumvioletred") +
  scale_y_continuous(breaks = round(seq(min(lt_plot$Globe), max(lt_plot$Globe), by = 0.1),1))+
  scale_x_continuous(name = "", breaks=seq(1,517,12), labels = manual_years)+
  geom_hline(yintercept = 0, alpha = 0.60, color ="darkgray") +
  labs(x = "",
       y = "T Departure from 91`-20` Average\n Deg. Celcius",
       title ="Latest Global Average Trophospheric Temperatures", size = 8)+
  theme(axis.text.x = element_text(angle = 90, size = 8),
        panel.background = element_rect(fill = "white", colour = "grey85"),
        panel.grid.major = element_line(colour = "gray92"),
        panel.grid.minor = element_line(colour = "gray98"))+
  annotate(geom="text", x=300, y=0.5, label="Running Centered\n13 Month Average",
         color="Black", size = 2.5)+
  annotate(geom = "segment", x = 270, xend = 250, y = 0.4, yend = 0.3,  color ="mediumvioletred",
           arrow = arrow(ends = "both", angle = 45, length = unit(.2,"cm")))+
  annotate(geom="text", x=80, y=0.5, 
           label="UAH Satellite-Based\nTemperature of the\nGlobal Lower Atmosphere\n [Version 6.0]",
           color="slateblue4", size = 3.5)
```

\newpage
**OPPGAVE 2**
```{r, results ='hide'}
#Lastet in datasettene en etter en. 
uahncdc_lt_6_0.txt <- fread("http://www.nsstc.uah.edu/data/msu/v6.0/tlt/uahncdc_lt_6.0.txt",
                            header = TRUE,
                            sep = "auto",
                            stringsAsFactors = FALSE,
                            fill = TRUE)

names(uahncdc_lt_6_0.txt)<-make.names(names(uahncdc_lt_6_0.txt),unique = TRUE)

uahncdc_mt_6_0.txt <- fread("https://www.nsstc.uah.edu/data/msu/v6.0/tmt/uahncdc_mt_6.0.txt",
                            header = TRUE,
                            sep = "auto",
                            stringsAsFactors = FALSE,
                            fill = TRUE)

names(uahncdc_mt_6_0.txt)<-make.names(names(uahncdc_mt_6_0.txt),unique = TRUE)

uahncdc_tp_6_0.txt <- fread("https://www.nsstc.uah.edu/data/msu/v6.0/ttp/uahncdc_tp_6.0.txt",
                            header = TRUE,
                            sep = "auto",
                            stringsAsFactors = FALSE,
                            fill = TRUE)

names(uahncdc_tp_6_0.txt)<-make.names(names(uahncdc_tp_6_0.txt),unique = TRUE)

uahncdc_ls_6_0.txt <- fread("https://www.nsstc.uah.edu/data/msu/v6.0/tls/uahncdc_ls_6.0.txt",
                            header = TRUE,
                            sep = "auto",
                            stringsAsFactors = FALSE,
                            fill = TRUE)

names(uahncdc_ls_6_0.txt)<-make.names(names(uahncdc_ls_6_0.txt),unique = TRUE)

```

```{r,out.lines = 5}
#kvitter meg med unødvendig kolonner og rader i alle datasettene
lt_raw <- select(uahncdc_lt_6_0.txt, -c(USA48, USA49, AUST))
str(lt_raw)

lt_raw1 <- lt_raw %>% slice(-c(518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529))

mt_raw <- select(uahncdc_mt_6_0.txt, -c(USA48, USA49, AUST))
str(mt_raw)

mt_raw1 <- mt_raw %>% slice(-c(518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529))

tp_raw <- select(uahncdc_tp_6_0.txt, -c(USA48, USA49, AUST))
str(tp_raw)

tp_raw1 <- tp_raw %>% slice(-c(518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529))

ls_raw <- select(uahncdc_ls_6_0.txt, -c(USA48, USA49, AUST))
str(ls_raw)

ls_raw1 <- ls_raw %>% slice(-c(518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529))

```

```{r, out.lines = 5}
#Velger ønskelige kolloner
lt_<-lt_raw1 %>% 
  select(Year, Mo, NoPol)
mt_<-mt_raw1 %>% 
  select(NoPol)
tp_<-tp_raw1 %>% 
  select(NoPol)
ls_<-ls_raw1 %>% 
  select(NoPol)
```

```{r, out.lines = 5}
#Samlet datasettene til ett ved hjelp av cbind()
#Deretter gjorde jeg om på navnene på kolonnene.
all_<- cbind(lt_, mt_,tp_,ls_)

names(all_)<-make.names(names(all_),unique = TRUE)

all_1<- all_ %>% 
  rename(NoPol_lt_ = NoPol,
         NoPol_mt_ = NoPol.1,
         NoPol_tp_ = NoPol.2,
         NoPol_ls_ = NoPol.3)

head(all_1)

```


```{r,out.lines = 5}
#Ville ha en tibble, deretter konverterte jeg de til numeric
as_tibble(all_1)

convert_to_numeric <- c("NoPol_lt_", "NoPol_mt_", "NoPol_tp_", "NoPol_ls_")

all_1[, convert_to_numeric] <- all_1[, lapply(.SD, as.numeric), .SDcols = convert_to_numeric]

```

```{r, out.lines=5}
#Utførte rowmeans() av alle NoPol kolonnene. Resultatet til ny kolonne
#kalt "Avg_NoPol".
#Deretter kjørte jeg rollmean av Avg_NoPol som jeg kalte for "thirteen_avg_NoPol"
all_2<-mutate(all_1, Avg_NoPol = rowMeans(select(all_1, ends_with("_")), na.rm = TRUE))

all_plot<- all_2 %>% mutate(thirteen_avg_NoPol = rollmean(Avg_NoPol, 13,
                                               align="right",
                                               fill=NA)) %>%
  relocate(thirteen_avg_NoPol)
str(all_plot)
```



```{r,  fig.width = 11, fig.height = 9}
#Jeg forsøkte forskjellige plot for å se hva som så mest oversiktelig ut.
#Endte opp med at geom_line() som for meg hvertfall var lettest å lese av.
#Prøvde å holde meg på samme linje visuelt som i Oppg1.
all_plot %>% 
  ggplot(aes(x = 1:517, group = 1))+
  geom_line(aes(y = NoPol_lt_), linetype = 1, lwd = 0.3, color ="royalblue4", lineend = "round")+
  geom_line(aes(y = NoPol_mt_), linetype = 1, lwd = 0.3, color ="darkorchid4", lineend = "round")+
  geom_line(aes(y = NoPol_tp_), linetype = 1, lwd = 0.3, color ="darkseagreen4", lineend = "round")+
  geom_line(aes(y = NoPol_ls_), linetype = 1, lwd = 0.3, color ="skyblue3", lineend = "round")+
  geom_line(aes(y = thirteen_avg_NoPol),linetype = 1, lwd = 0.7, lineend ="butt", color = "mediumvioletred") +
  scale_y_continuous(breaks = c(-9,-8,-7,-6,-5,-4,-3,-2,-2.5,-1.5,-1.0,-0.5,0.0,
                                           0.5,1.0,1.5,2.0,2.5,3,4,5,6,7,8,9)) +
  scale_x_continuous(name = "", breaks=seq(1,517,12), labels = manual_years)+
  geom_hline(yintercept = 0, alpha = 0.60, color ="darkgray") +
  labs(x = "",
       y = "T Departure from 91`-20` Average\n Deg. Celcius",
       title ="Latest Average Temperatures in\nThe North Polar Temperate Zone")+
  theme(axis.text.x = element_text(angle = 90, size = 7),
        axis.text.y = element_text(size = 7),
        panel.background = element_rect(fill = "white", colour = "grey85"),
        panel.grid.major = element_line(colour = "gray92"),
        panel.grid.minor = element_line(colour = "gray98"))+
  annotate(geom="text", x=170, y=-6.0, label="Running Centered\n13 Month Average",
           color="Black", size = 2.5)+
  annotate(geom = "segment", x = 150, xend = 150, y = -5.0, yend = -1.0,  color ="mediumvioletred",
           arrow = arrow(ends = "both", angle = 45, length = unit(.2,"cm")))+
  annotate(geom="text", x=190, y=8.0, 
           label="UAH Satellite-Based\nTemperature of the\nNorthern Polar Temperate Zone\n[Version 6.0]",
           color="slateblue4", size = 3.0)+
  annotate(geom="text", x=450, y=-6.5, 
           label="-Lower Trophospshere-",
           color="royalblue4", size = 2.5)+
  annotate(geom="text", x=443, y=-7.0, 
           label="-Mid Troposphere-",
           color="darkorchid4", size = 2.5)+
  annotate(geom="text", x=439, y=-7.4,
           label="-Tropopause-",
           color="darkseagreen4", size = 2.5)+
  annotate(geom="text", x=448, y=-7.8, 
           label="-Lower Stratosphere-",
           color="skyblue3", size = 2.5)
```



